version: "3"
services: 
    back-end:
        container_name: back-end
        volumes:
            - api:/apimodelos/shared/api
            - components:/apimodelos/shared/components
        build: 
            context: ./backend
            dockerfile: ./Dockerfile
        restart: always
        links:
            - mongo
            - strapi
        networks:
            default:
              aliases:
                - front-end
    mongo:
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: StrapiAPI
            MONGO_INITDB_DATABASE: LEI2021
        image: mongo
    front-end:
        container_name: front-end
        restart: always
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports: 
            - "12080:80"
        links:
            - back-end
            - strapi
        networks:
            default:
              aliases:
                - back-end
    dfs-front-end:
        container_name: dfs-front-end
        restart: always
        build:
            context: ./dfs_frontend
            dockerfile: ./Dockerfile
        ports: 
            - "12081:80"
        links:
            - back-end
        networks:
            default:
              aliases:
                - back-end
    strapi:
        image: strapi/strapi
        container_name: strapi
        restart: always
        build: 
            context: ./strapi
            dockerfile: ./Dockerfile
        volumes:
            - api:/StrapiAPI/api
            - components:/StrapiAPI/components
        environment:
            DATABASE_CLIENT: mongo
            DATABASE_NAME: StrapiAPI
            DATABASE_HOST: mongo
            DATABASE_PORT: 27017
        depends_on:
            - mongo
volumes:
    api:
    components: